apiVersion: v1
kind: Service
metadata:
  name: load-balancer
spec:
  selector:
    app: load-balancer
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-balancer
spec:
  selector:
    matchLabels:
      app: load-balancer
  replicas: 1
  template:
    metadata:
      labels:
        app: load-balancer
    spec:
      containers:
        - name: load-balancer
          image: load-balancer
          ports:
            - containerPort: 8080
